cm3070final/base/urls.py
from django.urls import path
from .views import home_view

urlpatterns = [
    path('', home_view, name='home'),
]

cm3070final/opportunities_engagements/urls.py
from django.urls import path
from .views import opportunities_search_view, opportunities_organization_view, opportunity_view, engagements_applications_log_requests_view, applications_log_requests_view
from .api import get_opportunity, get_opportunities, get_nearby_opportunities, get_latest_opportunities, get_upcoming_opportunities, create_opportunity, get_organization_opportunities, cancel_opportunity, complete_opportunity, create_application, accept_application, reject_application, cancel_application, get_volunteer_applications, get_organization_applications, create_engagement, get_engagements, get_opportunity_engagements, complete_engagements_organization, cancel_engagement_volunteer, cancel_engagements_organization, create_session, get_sessions, complete_session, cancel_session, create_session_engagements_for_session, create_session_engagements_for_volunteer, confirm_attendance, cancel_attendance, get_session_engagements, get_volunteer_session_engagements, create_opportunity_engagement_logs, create_session_engagement_logs, create_engagement_log_volunteer, approve_engagement_log, reject_engagement_log, get_organization_log_requests, get_engagement_logs, get_volunteer_log_requests

app_name = 'opportunities_engagements'

urlpatterns = [
    ### View endpoints ###
    path('opportunities_search/', opportunities_search_view, name='opportunities_search'),
    path('opportunities_organization/', opportunities_organization_view, name='opportunities_organization'),
    path('opportunity/<uuid:opportunity_id>/', opportunity_view, name='opportunity'),
    path('engagements_applications_log_requests/', engagements_applications_log_requests_view, name='engagements_applications_log_requests'),
    path('applications_log_requests/', applications_log_requests_view, name='applications_log_requests'),
    
    ### REST API Endpoints ###
    ### Opportunities ###
    path('api/opportunities/get_opportunity<uuid:opportunity_id>/', get_opportunity, name='get_opportunity'), # done - doesnt need event listener
    path('api/opportunities/get_opportunities/', get_opportunities, name='get_opportunities'), # user search page - doesnt need event listener
    path('api/opportunities/get_nearby_opportunities/', get_nearby_opportunities, name='get_nearby_opportunities'), # done - doesnt need event listener
    path('api/opportunities/get_latest_opportunities/', get_latest_opportunities, name='get_latest_opportunities'), # done - doesnt need event listener
    path('api/opportunities/get_upcoming_opportunities/<uuid:account_uuid>', get_upcoming_opportunities, name='get_upcoming_opportunities'), # done - doesnt need event listener - used in profile page
    path('api/opportunities/create_opportunity/', create_opportunity, name='create_opportunity'), # done - needs event listener - DONE
    path('api/opportunities/get_organization_opportunities/', get_organization_opportunities, name='get_organization_opportunities'), # done - doesnt need event listener
    path('api/opportunities/cancel_opportunity/<uuid:volunteer_opportunity_id>/', cancel_opportunity, name='cancel_opportunity'), # needs event listener - executeChainedActions - done
    path('api/opportunities/complete_opportunity/<uuid:volunteer_opportunity_id>/', complete_opportunity, name='complete_opportunity'), #needs event listener - executeChainedActions - done

    ### Applications ###
    path('api/opportunities/applications/create/<uuid:volunteer_opportunity_id>/', create_application, name='create_application'), # done - needs event listener - DONE
    path('api/opportunities/applications/accept/<uuid:application_id>/', accept_application, name='accept_application'), # done - needs event listener - to call together with create_engagement and create_session_engagements_for_volunteer
    path('api/opportunities/applications/reject/<uuid:application_id>/', reject_application, name='reject_application'), # done - needs evenet listener - DONE
    path('api/opportunities/applications/cancel/<uuid:application_id>/', cancel_application, name='cancel_application'), # done - needs event listener - DONE
    path('api/opportunities/applications/volunteer/<uuid:account_uuid>/', get_volunteer_applications, name='get_volunteer_applications'), # done - doesnt need event listener
    path('api/opportunities/applications/organization/<uuid:account_uuid>/', get_organization_applications, name='get_organization_applications'), # done - doesnt need event listener
    
    ### Engagements ###
    path('api/engagements/create_engagement/<uuid:application_id>/', create_engagement, name='create_engagement'), # doesnt need event listener - to call together with accept_application and create_session_engagements_for_session
    path('api/engagements/get_engagements/<uuid:account_uuid>/', get_engagements, name='get_engagements'), # done - doesnt need event listener - used in engagements_applications_log_requests page
    path('api/engagements/get_opportunity_engagements/<uuid:volunteer_opportunity_id>/', get_opportunity_engagements, name='get_opportunity_engagements'), # done - doesnt need event listener - called when opening modal prior to completing an opportunity
    path('api/engagements/complete_engagements_organization/<uuid:volunteer_opportunity_id>/', complete_engagements_organization, name='complete_engagements_organization'), # needs event listener - to call together with complete_opportunity and create_opportunity_engagement_logs
    path('api/engagements/cancel_engagement_volunteer/<uuid:volunteer_engagement_id>/', cancel_engagement_volunteer, name='cancel_engagement_volunteer'), # done - needs event listener - DONE
    path('api/engagements/cancel_engagements_organization/<uuid:volunteer_opportunity_id>/', cancel_engagements_organization, name='cancel_engagements_organization'), # needs event listener - to call together with cancel_opportunity
    
    ### Sessions ###
    path('api/sessions/create_session/<uuid:opportunity_id>/', create_session, name='create_session'), # needs event listener - to call together with create_session_engagements_for_session
    path('api/sessions/get_sessions/<uuid:opportunity_id>/', get_sessions, name='get_sessions'), # done - doesnt need event listener
    path('api/sessions/complete_session/<uuid:session_id>/', complete_session, name='complete_session'), # needs event listener - to call together with create_session_engagement_logs
    path('api/sessions/cancel_session/<uuid:session_id>/', cancel_session, name='cancel_session'), # done - needs event listener - DONE

    ### Session Engagements ###
    path('api/session_engagements/create_session_engagements_for_session/<uuid:session_id>/', create_session_engagements_for_session, name='create_session_engagements_for_session'), # needs event listener - to call together with create_session
    path('api/session_engagements/create_session_engagements_for_volunteer/<uuid:account_uuid>/<uuid:opportunity_id>/', create_session_engagements_for_volunteer, name='create_session_engagements_for_volunteer'), # needs event listener - to call together with accept_application
    path('api/session_engagements/confirm_attendance/<uuid:session_engagement_id>/', confirm_attendance, name='confirm_attendance'), # done - needs event listener - DONE
    path('api/session_engagements/cancel_attendance/<uuid:session_engagement_id>/', cancel_attendance, name='cancel_attendance'), # done - needs event listener - DONE
    path('api/session_engagements/get_session_engagements/<uuid:session_id>/', get_session_engagements, name='get_session_engagements'), # done - doesnt need event listener
    path('api/session_engagements/get_volunteer_session_engagements/<uuid:account_uuid>/', get_volunteer_session_engagements, name='get_volunteer_session_engagements'), # done - doesnt need event listener (called in opportunity page to match a users session engagements with the sessions found)

    ### Engagement Logs
    path('api/engagement_logs/create_opportunity_engagement_logs/<uuid:opportunity_id>/', create_opportunity_engagement_logs, name='create_opportunity_engagement_logs'), # executeChainedActions needs event listener - to call together with complete_opportunity - done
    path('api/engagement_logs/create_session_engagement_logs/<uuid:session_id>/', create_session_engagement_logs, name='create_session_engagement_logs'), # executeChainedActions needs event listener - to call together with complete_session - done
    path('api/engagement_logs/create_engagement_log_volunteer/<uuid:opportunity_id>/', create_engagement_log_volunteer, name='create_engagement_log_volunteer'), # done - needs event listener - DONE
    path('api/engagement_logs/approve_engagement_log/<uuid:volunteer_engagement_log_id>/', approve_engagement_log, name='approve_engagement_log'), # done - needs event listener - DONE
    path('api/engagement_logs/reject_engagement_log/<uuid:volunteer_engagement_log_id>/', reject_engagement_log, name='reject_engagement_log'), # done - needs event listener - DONE
    path('api/engagement_logs/get_organization_log_requests/<uuid:account_uuid>/', get_organization_log_requests, name='get_organization_log_requests'), # done - used in applications_log_requests - doesnt need event listener
    path('api/engagement_logs/get_engagement_logs/<uuid:account_uuid>/', get_engagement_logs, name='get_engagement_logs'), # used in profile page - doesnt need event listener - done
    path('api/engagement_logs/get_volunteer_log_requests/<uuid:account_uuid>/', get_volunteer_log_requests, name='get_volunteer_log_requests'), # done - used in engagements_applications_log_requests page - doesnt need event listener
]

cm3070final/volontera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpRequest
from base import views as base_views

# Custom error handlers
handler404 = base_views.custom_404
handler403 = base_views.custom_403
handler500 = base_views.custom_500
handler400 = base_views.custom_400

def root_redirect_view(request: HttpRequest):
    if request.user.is_authenticated:
        return redirect(f'/volunteers-organizations/profile/{request.user.account_uuid}')
    return redirect('/accounts/auth/?type=login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root_redirect_view),
    path('home/', lambda request: redirect('/')), # Redirect to home
    path('accounts/', include('accounts_notifs.urls')),
    path('volunteers-organizations/', include('volunteers_organizations.urls')),
    path('oauth/', include('allauth.urls')),
    path('opportunities-engagements/', include('opportunities_engagements.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cm3070final/opportunities_engagements/templates/opportunities_engagements/partials/apply_opportunity_modal.html
{% load static %}

<div id="apply-opportunity-modal" class="fixed inset-0 items-center justify-center bg-black bg-opacity-50 hidden">
    <div class="bg-white p-8 rounded-lg shadow-lg w-4/5 max-w-4xl max-h-[80vh] overflow-y-auto">
        <!-- Modal Header -->
        <div class="flex justify-center relative mb-4">
            <h2 class="text-2xl font-bold mx-auto">Apply for Opportunity</h2>
            <button onclick="document.getElementById('apply-opportunity-modal').classList.add('hidden'); document.getElementById('apply-opportunity-modal').classList.remove('flex'); document.getElementById('create-application-form').reset(); toggleGroupApplication();" 
                class="absolute right-0 text-gray-500 hover:text-gray-700">✕
            </button>
        </div>

        <form id="create-application-form" 
              method="post"
              hx-post="{% url 'opportunities_engagements:create_application' opportunity.volunteer_opportunity_id %}"
              hx-trigger="submit"
              hx-target="#loading-modal-content"
              hx-swap="innerHTML"
              class="space-y-6">
            
            {% if not opportunity.ongoing %}
                <!-- Apply as Group? -->
                <div class="bg-gray-100 p-4 rounded-lg">
                    <label class="flex items-center space-x-2">
                        <input type="checkbox" id="as_group" name="as_group" value="true" onchange="toggleGroupApplication()">
                        <span class="text-gray-800">Apply as a Group</span>
                    </label>
                </div>

                <!-- Number of Additional Volunteers (Shown Only if Applying as Group) -->
                <div id="group-size-container" class="bg-gray-100 p-4 rounded-lg hidden">
                    <label class="block text-gray-700 font-semibold mb-2">Number of Additional Volunteers</label>
                    <input type="number" name="no_of_additional_volunteers" min="1" placeholder="Enter number of additional volunteers"
                        class="w-full text-sm text-gray-800 bg-white focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">
                </div>
            {% endif %}

            <!-- Rationale for Applying -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Why do you want to apply?</label>
                <textarea name="rationale" rows="4" placeholder="Provide a brief explanation (Optional)"
                          class="w-full text-sm text-gray-800 bg-white focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600"></textarea>
            </div>
            
            <!-- Hidden Fields -->
            <input type="hidden" name="volunteer_opportunity" value="{{ opportunity.volunteer_opportunity_id }}">
            
            <!-- Submit & Cancel Buttons -->
            <div class="flex justify-between mt-6">
                <button type="button" onclick="document.getElementById('apply-opportunity-modal').classList.add('hidden')" 
                        class="bg-gray-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-gray-700">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                          </svg>
                    <span class="font-bold">Cancel</span>                           
                </button>
                <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-blue-700">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                      </svg>                      
                    <span class="font-bold">Apply</span>
                </button>
            </div>
        </form>
    </div>
</div>

cm3070final/opportunities_engagements/templates/opportunities_engagements/partials/create_engagement_log_modal.html
{% load static %}
<div id="create-engagement-log-modal" class="fixed inset-0 items-center justify-center bg-black z-50 bg-opacity-50 hidden">
    <div class="bg-white p-8 rounded-lg shadow-lg w-4/5 max-w-4xl max-h-[80vh] overflow-y-auto">
        <!-- Modal Header -->
        <div class="flex justify-center relative mb-4">
            <h2 class="text-2xl font-bold mx-auto">Create Engagement Log</h2>
            <button onclick="document.getElementById('create-engagement-log-modal').classList.add('hidden')" 
                class="absolute right-0 text-gray-500 hover:text-gray-700">✕
            </button>
        </div>

        <form id="create-engagement-log-form" 
              method="post"
              hx-post="{% url 'opportunities_engagements:create_engagement_log_volunteer' opportunity.volunteer_opportunity_id %}"
              hx-trigger="submit"
              hx-target="#loading-modal-content"
              hx-swap="innerHTML"
              class="space-y-6">
            
            <!-- Number of Hours -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Number of Hours</label>
                <input type="number" name="no_of_hours" required step="0.5" min="0.5" max="12"
                       placeholder="Enter the number of hours worked"
                       class="w-full text-sm text-gray-800 bg-white focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">
            </div>

            <!-- Log Notes -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Log Notes</label>
                <textarea name="log_notes" rows="4" required placeholder="Describe your engagement activity (Upon acceptance this will be listed along your contributions on your profile page)"
                          class="w-full text-sm text-gray-800 bg-white focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600"></textarea>
            </div>

            <!-- Hidden Fields -->
            <input type="hidden" name="status" value="pending">
            <input type="hidden" name="is_volunteer_request" value="true">
            
            <!-- Submit & Cancel Buttons -->
            <div class="flex justify-between mt-6">
                <button type="button" onclick="document.getElementById('create-engagement-log-modal').classList.add('hidden')" 
                        class="bg-gray-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-gray-700">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                          </svg>
                    <span class="font-bold">Cancel</span>                           
                </button>
                <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-blue-700">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                      </svg>                      
                    <span class="font-bold">Submit Log</span>
                </button>
            </div>
        </form>
    </div>
</div>

cm3070final/opportunities_engagements/templates/opportunities_engagements/partials/create_opportunity_modal.html
{% load static %}
<div id="create-opportunity-modal" class="fixed inset-0 items-center justify-center bg-black bg-opacity-50 hidden">
    <div class="bg-white p-8 rounded-lg shadow-lg w-4/5 max-w-4xl max-h-[80vh] overflow-y-auto">
        <!-- Modal Header -->
        <div class="flex justify-between items-start relative mb-4">
            <div class="flex flex-col">
                <h2 class="text-2xl font-bold">Create a New Opportunity</h2>
                <h3 class="text-xs text-gray-500 mt-1">
                    Please fill in the details below (if Invalid JSON error pops up, try re-entering the location in the Location field)
                </h3>
            </div>
            <button onclick="document.getElementById('create-opportunity-modal').classList.add('hidden'); document.getElementById('create-opportunity-modal').classList.remove('flex'); document.getElementById('create-opportunity-form').reset()" 
                class="absolute right-0 text-gray-500 hover:text-gray-700">✕
            </button>
        </div>

        <form id="create-opportunity-form" 
              method="post"
              hx-post="{% url 'opportunities_engagements:create_opportunity' %}"
              hx-trigger="submit"
              hx-target="#loading-modal-content"
              hx-swap="innerHTML"
              class="space-y-6">
            <!-- Opportunity Title -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Title</label>
                <input type="text" name="title" required placeholder="Enter Opportunity Title"
                       class="w-full text-sm text-gray-800 bg-white focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">
            </div>

            <!-- Opportunity Description -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Description</label>
                <input type="text" name="description" required placeholder="Enter Opportunity Description"
                       class="w-full text-sm text-gray-800 bg-white focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">
            </div>

            <!-- Opportunity Type (One-Time or Ongoing) -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Opportunity Type</label>
                <div class="flex space-x-4">
                    <label class="flex items-center space-x-2">
                        <input type="radio" name="ongoing" value="false" checked onchange="toggleOpportunityType()">
                        <span>One-Time</span>
                    </label>
                    <label class="flex items-center space-x-2">
                        <input type="radio" name="ongoing" value="true" onchange="toggleOpportunityType()">
                        <span>Ongoing</span>
                    </label>
                </div>
            </div>

            <!-- Location -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label for="location-input" class="block text-gray-700 font-semibold mb-2">Preferred Location</label>
                <input id="location-input" required="true" name="location_input" value="{{ preferences.location.formatted_address}}"
                    class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">
                <!-- Hidden input to store location data -->
                <input type="hidden" id="location-hidden" name="required_location" value="{{ preferences.location }}">
            </div>

            <!-- Required Languages -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label for="language-select" class="block text-gray-700 font-semibold mb-2">Languages</label>
                <select id="language-select" name="languages" multiple class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 rounded-md outline-blue-600">
                    {% for code, lang in languages %}
                        <option value="{{ lang }}">{{ lang }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- One-Time Opportunity Fields -->
            <div id="one-time-fields" class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Date & Time</label>
                <div class="flex space-x-4">
                    <input type="date" name="opportunity_date" class="w-full text-sm text-gray-800 bg-white rounded-md outline-blue-600">
                    <input type="time" name="opportunity_time_from" class="w-full text-sm text-gray-800 bg-white rounded-md outline-blue-600">
                    <input type="time" name="opportunity_time_to" class="w-full text-sm text-gray-800 bg-white rounded-md outline-blue-600">
                </div>
                <label class="block text-gray-700 font-semibold mt-2">Application Deadline</label>
                <input type="date" name="application_deadline" class="w-full text-sm text-gray-800 bg-white rounded-md outline-blue-600">
                <div class="flex flex-col mt-4">
                    <label class="block text-gray-700 font-semibold">Slots Available</label>
                    <input type="number" name="slots" min="1" placeholder="Number of places available"
                           class="w-full text-sm text-gray-800 bg-white rounded-md outline-blue-600">
                </div>

                <!-- Can Apply as Group -->
                <div class="mt-4">
                    <label class="flex items-center space-x-2">
                        <input type="checkbox" name="can_apply_as_group">
                        <span>Allow group applications</span>
                    </label>
                </div>
            </div>

            <!-- Ongoing Opportunity Fields -->
            <div id="ongoing-fields" class="bg-gray-100 p-4 rounded-lg hidden">
                <!-- Availability (Days of the Week) -->
                <label class="block text-gray-700 font-semibold mb-2">Availability (Days of the Week)</label>
                <div class="grid grid-cols-3 gap-4">
                    {% for day in days_of_week %}
                        <label class="flex items-center space-x-2">
                            <input type="checkbox" name="days_of_week" value="{{ day }}">
                            <span>{{ day|title }}</span>
                        </label>
                    {% endfor %}
                </div>
            </div>

            <!-- Work Type -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Work Type</label>
                <select name="work_basis" class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md 
                focus:ring-2 focus:ring-blue-600 focus:border-blue-600">
                    {% for type in work_types %}
                        <option value="{{ type }}">{{ type|title }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- Duration (Short-Term for One-Time, Selectable for Ongoing) -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Duration</label>
                <select name="duration" id="duration-select" class="w-full text-sm text-gray-800 bg-white rounded-md outline-blue-600" disabled>
                    <option value="short-term" selected>Short-Term</option>
                    <option value="medium-term">Medium-Term</option>
                    <option value="long-term">Long-Term</option>
                </select>
            </div>

            <!-- Area of Work (Single Selection Dropdown) -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Area of Work</label>
                <select name="area_of_work" required 
                        class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">
                    {% for field in area_of_work %}
                        <option value="{{ field }}">{{ field|title }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- Requirements -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-2">Required skills</label>
                <div class="grid grid-cols-3 gap-4">
                    {% for skill in requirements %}
                        <label class="flex items-center space-x-2">
                            <input type="checkbox" name="requirements" value="{{ skill }}" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                            <span>{{ skill|title }}</span>
                        </label>
                    {% endfor %}
                </div>
            </div>
            
            <!-- Submit & Cancel Buttons -->
            <div class="flex justify-between mt-6">
                <button type="button" onclick="document.getElementById('create-opportunity-modal').classList.add('hidden')" 
                        class="bg-gray-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-gray-700">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                          </svg>
                    <span class="font-bold">Cancel</span>                          
                </button>
                <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-blue-700">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                      </svg>                      
                    <span class="font-bold">Create Opportunity</span>
                </button>
            </div>
        </form>
    </div>
</div>

cm3070final/opportunities_engagements/templates/opportunities_engagements/partials/view_opportunity_engagees_modal.html
<div id="engagees-modal" class="fixed inset-0 bg-gray-900 z-50 bg-opacity-50 items-center justify-center hidden">
    <div class="bg-white p-6 rounded-lg shadow-lg w-1/3">
        <h2 class="text-xl font-bold mb-2">Engaged Volunteers</h2>
        <div id="engagees-modal-content">
            <p class="text-gray-500">Loading...</p>
        </div>
        <div class="flex justify-center items-center mt-4">
            <button onclick="document.getElementById('engagees-modal').classList.add('hidden'); document.getElementById('engagees-modal').classList.remove('flex')" 
                class="bg-red-500 text-white px-4 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-red-700">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                </svg>
                <span class="font-bold">Close</span>
            </button>
        </div>
    </div>
</div>