cm3070final/base/urls.py
from django.urls import path
from .views import home_view

urlpatterns = [
    path('', home_view, name='home'),
]

cm3070final/opportunities_engagements/urls.py
from django.urls import path
from .views import opportunities_search_view, opportunities_organization_view, opportunity_view, engagements_applications_log_requests_view, applications_log_requests_view
from .api import get_opportunity, get_opportunities, get_nearby_opportunities, get_latest_opportunities, get_upcoming_opportunities, create_opportunity, get_organization_opportunities, cancel_opportunity, complete_opportunity, create_application, accept_application, reject_application, cancel_application, get_volunteer_applications, get_organization_applications, create_engagement, get_engagements, get_opportunity_engagements, complete_engagements_organization, cancel_engagement_volunteer, cancel_engagements_organization, create_session, get_sessions, complete_session, cancel_session, create_session_engagements_for_session, create_session_engagements_for_volunteer, confirm_attendance, cancel_attendance, get_session_engagements, get_volunteer_session_engagements, create_opportunity_engagement_logs, create_session_engagement_logs, create_engagement_log_volunteer, approve_engagement_log, reject_engagement_log, get_organization_log_requests, get_engagement_logs, get_volunteer_log_requests

app_name = 'opportunities_engagements'

urlpatterns = [
    ### View endpoints ###
    path('opportunities_search/', opportunities_search_view, name='opportunities_search'),
    path('opportunities_organization/', opportunities_organization_view, name='opportunities_organization'),
    path('opportunity/<uuid:opportunity_id>/', opportunity_view, name='opportunity'),
    path('engagements_applications_log_requests/', engagements_applications_log_requests_view, name='engagements_applications_log_requests'),
    path('applications_log_requests/', applications_log_requests_view, name='applications_log_requests'),
    
    ### REST API Endpoints ###
    ### Opportunities ###
    path('api/opportunities/get_opportunity<uuid:opportunity_id>/', get_opportunity, name='get_opportunity'), # done - doesnt need event listener
    path('api/opportunities/get_opportunities/', get_opportunities, name='get_opportunities'), # user search page - doesnt need event listener
    path('api/opportunities/get_nearby_opportunities/', get_nearby_opportunities, name='get_nearby_opportunities'), # done - doesnt need event listener
    path('api/opportunities/get_latest_opportunities/', get_latest_opportunities, name='get_latest_opportunities'), # done - doesnt need event listener
    path('api/opportunities/get_upcoming_opportunities/<uuid:account_uuid>', get_upcoming_opportunities, name='get_upcoming_opportunities'), # done - doesnt need event listener - used in profile page
    path('api/opportunities/create_opportunity/', create_opportunity, name='create_opportunity'), # done - needs event listener - DONE
    path('api/opportunities/get_organization_opportunities/', get_organization_opportunities, name='get_organization_opportunities'), # done - doesnt need event listener
    path('api/opportunities/cancel_opportunity/<uuid:volunteer_opportunity_id>/', cancel_opportunity, name='cancel_opportunity'), # needs event listener - executeChainedActions - done
    path('api/opportunities/complete_opportunity/<uuid:volunteer_opportunity_id>/', complete_opportunity, name='complete_opportunity'), #needs event listener - executeChainedActions - done

    ### Applications ###
    path('api/opportunities/applications/create/<uuid:volunteer_opportunity_id>/', create_application, name='create_application'), # done - needs event listener - DONE
    path('api/opportunities/applications/accept/<uuid:application_id>/', accept_application, name='accept_application'), # done - needs event listener - to call together with create_engagement and create_session_engagements_for_volunteer
    path('api/opportunities/applications/reject/<uuid:application_id>/', reject_application, name='reject_application'), # done - needs evenet listener - DONE
    path('api/opportunities/applications/cancel/<uuid:application_id>/', cancel_application, name='cancel_application'), # done - needs event listener - DONE
    path('api/opportunities/applications/volunteer/<uuid:account_uuid>/', get_volunteer_applications, name='get_volunteer_applications'), # done - doesnt need event listener
    path('api/opportunities/applications/organization/<uuid:account_uuid>/', get_organization_applications, name='get_organization_applications'), # done - doesnt need event listener
    
    ### Engagements ###
    path('api/engagements/create_engagement/<uuid:application_id>/', create_engagement, name='create_engagement'), # doesnt need event listener - to call together with accept_application and create_session_engagements_for_session
    path('api/engagements/get_engagements/<uuid:account_uuid>/', get_engagements, name='get_engagements'), # done - doesnt need event listener - used in engagements_applications_log_requests page
    path('api/engagements/get_opportunity_engagements/<uuid:volunteer_opportunity_id>/', get_opportunity_engagements, name='get_opportunity_engagements'), # done - doesnt need event listener - called when opening modal prior to completing an opportunity
    path('api/engagements/complete_engagements_organization/<uuid:volunteer_opportunity_id>/', complete_engagements_organization, name='complete_engagements_organization'), # needs event listener - to call together with complete_opportunity and create_opportunity_engagement_logs
    path('api/engagements/cancel_engagement_volunteer/<uuid:volunteer_engagement_id>/', cancel_engagement_volunteer, name='cancel_engagement_volunteer'), # done - needs event listener - DONE
    path('api/engagements/cancel_engagements_organization/<uuid:volunteer_opportunity_id>/', cancel_engagements_organization, name='cancel_engagements_organization'), # needs event listener - to call together with cancel_opportunity
    
    ### Sessions ###
    path('api/sessions/create_session/<uuid:opportunity_id>/', create_session, name='create_session'), # needs event listener - to call together with create_session_engagements_for_session
    path('api/sessions/get_sessions/<uuid:opportunity_id>/', get_sessions, name='get_sessions'), # done - doesnt need event listener
    path('api/sessions/complete_session/<uuid:session_id>/', complete_session, name='complete_session'), # needs event listener - to call together with create_session_engagement_logs
    path('api/sessions/cancel_session/<uuid:session_id>/', cancel_session, name='cancel_session'), # done - needs event listener - DONE

    ### Session Engagements ###
    path('api/session_engagements/create_session_engagements_for_session/<uuid:session_id>/', create_session_engagements_for_session, name='create_session_engagements_for_session'), # needs event listener - to call together with create_session
    path('api/session_engagements/create_session_engagements_for_volunteer/<uuid:account_uuid>/<uuid:opportunity_id>/', create_session_engagements_for_volunteer, name='create_session_engagements_for_volunteer'), # needs event listener - to call together with accept_application
    path('api/session_engagements/confirm_attendance/<uuid:session_engagement_id>/', confirm_attendance, name='confirm_attendance'), # done - needs event listener - DONE
    path('api/session_engagements/cancel_attendance/<uuid:session_engagement_id>/', cancel_attendance, name='cancel_attendance'), # done - needs event listener - DONE
    path('api/session_engagements/get_session_engagements/<uuid:session_id>/', get_session_engagements, name='get_session_engagements'), # done - doesnt need event listener
    path('api/session_engagements/get_volunteer_session_engagements/<uuid:account_uuid>/', get_volunteer_session_engagements, name='get_volunteer_session_engagements'), # done - doesnt need event listener (called in opportunity page to match a users session engagements with the sessions found)

    ### Engagement Logs
    path('api/engagement_logs/create_opportunity_engagement_logs/<uuid:opportunity_id>/', create_opportunity_engagement_logs, name='create_opportunity_engagement_logs'), # executeChainedActions needs event listener - to call together with complete_opportunity - done
    path('api/engagement_logs/create_session_engagement_logs/<uuid:session_id>/', create_session_engagement_logs, name='create_session_engagement_logs'), # executeChainedActions needs event listener - to call together with complete_session - done
    path('api/engagement_logs/create_engagement_log_volunteer/<uuid:opportunity_id>/', create_engagement_log_volunteer, name='create_engagement_log_volunteer'), # done - needs event listener - DONE
    path('api/engagement_logs/approve_engagement_log/<uuid:volunteer_engagement_log_id>/', approve_engagement_log, name='approve_engagement_log'), # done - needs event listener - DONE
    path('api/engagement_logs/reject_engagement_log/<uuid:volunteer_engagement_log_id>/', reject_engagement_log, name='reject_engagement_log'), # done - needs event listener - DONE
    path('api/engagement_logs/get_organization_log_requests/<uuid:account_uuid>/', get_organization_log_requests, name='get_organization_log_requests'), # done - used in applications_log_requests - doesnt need event listener
    path('api/engagement_logs/get_engagement_logs/<uuid:account_uuid>/', get_engagement_logs, name='get_engagement_logs'), # used in profile page - doesnt need event listener - done
    path('api/engagement_logs/get_volunteer_log_requests/<uuid:account_uuid>/', get_volunteer_log_requests, name='get_volunteer_log_requests'), # done - used in engagements_applications_log_requests page - doesnt need event listener
]

cm3070final/volontera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpRequest
from base import views as base_views

# Custom error handlers
handler404 = base_views.custom_404
handler403 = base_views.custom_403
handler500 = base_views.custom_500
handler400 = base_views.custom_400

def root_redirect_view(request: HttpRequest):
    if request.user.is_authenticated:
        return redirect(f'/volunteers-organizations/profile/{request.user.account_uuid}')
    return redirect('/accounts/auth/?type=login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root_redirect_view),
    path('home/', lambda request: redirect('/')), # Redirect to home
    path('accounts/', include('accounts_notifs.urls')),
    path('volunteers-organizations/', include('volunteers_organizations.urls')),
    path('oauth/', include('allauth.urls')),
    path('opportunities-engagements/', include('opportunities_engagements.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cm3070final/volunteers_organizations/urls.py
from django.urls import path
from .views import signup_final, profile_view, search_profiles_view, update_profile_view, preferences_view
from .api import get_user_profile, get_all_followers, get_following, create_following, delete_following, get_endorsements, create_endorsement, delete_endorsement, get_status_posts, create_status_post, delete_status_post, get_search_profiles, create_volunteer_preferences, create_organization_preferences, get_organization_preferences, get_volunteer_preferences, update_volunteer_preferences, update_organization_preferences, donate_volontera_points

app_name = 'volunteers_organizations'

urlpatterns = [
    # View endpoints
    path('signup_final/', signup_final, name='signup_final'),
    path('profile/<uuid:account_uuid>', profile_view, name='profile'),
    path('search_profiles/', search_profiles_view, name='search_profiles'),
    path('update_profile/', update_profile_view, name='update_profile'),
    path('preferences/', preferences_view, name='preferences'),

    ### REST API Endpoints ###
    # Account profile endpoints
    path('api/profile/<uuid:account_uuid>', get_user_profile, name='get_user_profile'),
    
    # Following endpoints
    path('api/following/get_all_followers/<uuid:account_uuid>', get_all_followers, name='get_all_followers'),
    path('api/following/get_following/<uuid:account_uuid>', get_following, name='get_following'),
    path('api/following/create_following/<uuid:account_uuid>', create_following, name='create_following'),
    path('api/following/delete_following/<uuid:account_uuid>', delete_following, name='delete_following'),
    
    # Endorsement endpoints
    path('api/endorsements/get_endorsements/<uuid:account_uuid>', get_endorsements, name='get_endorsements'),
    path("api/endorsements/create_endorsement/<uuid:account_uuid>/", create_endorsement, name="create_endorsement"),
    path("api/endorsements/delete_endorsement/<uuid:id>/", delete_endorsement, name="delete_endorsement"),
    
    # Status post endpoints
    path("api/status_posts/get_status_posts/<uuid:account_uuid>/", get_status_posts, name="get_status_posts"),
    path("api/status/create_status_post/", create_status_post, name="create_status_post"),
    path("api/status/delete_status_post/<uuid:id>/", delete_status_post, name="delete_status_post"),
    
    # Search profiles endpoints
    path("api/search/get_search_profiles/", get_search_profiles, name="get_search_profiles"),
    
    #Volunteer Matching/Organization Preferences
    path('api/volunteer_matching_preferences/create_volunteer_preferences/', create_volunteer_preferences, name='create_volunteer_preferences'),
    path('api/volunteer_matching_preferences/get_volunteer_preferences/', get_volunteer_preferences, name='get_volunteer_preferences'),
    path('api/volunteer_matching_preferences/update_volunteer_preferences/', update_volunteer_preferences, name='update_volunteer_preferences'),
    path('api/organization_preferences/create_organization_preferences/', create_organization_preferences, name='create_organization_preferences'),
    path('api/organization_preferences/get_organization_preferences/', get_organization_preferences, name='get_organization_preferences'),
    path('api/organization_preferences/update_organization_preferences/', update_organization_preferences, name='update_organization_preferences'),

    # Donate endpoints
    path('api/donate/donate_volontera_points/<uuid:organization_id>', donate_volontera_points, name='donate_volontera_points'),
]

cm3070final/opportunities_engagements/templates/opportunities_engagements/applications_log_requests.html
{% extends 'base/base_authenticated.html' %}
{% load static %}
{% block title %}Engagements & Applications{% endblock %}
{% block auth_content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css">
<script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_PLACES_API_KEY }}&libraries=places&callback=initAutocomplete" async defer></script>
<script>var csrftoken = '{{ csrf_token }}';</script>
<script src="{% static 'js_frontend-scripts/profile-processes.js' %}"></script>
<script src="{% static 'js_frontend-scripts/preferences-processes.js' %}"></script>
<script src="{% static 'js_frontend-scripts/opportunities-engagements-processes.js' %}"></script>
<style>
    .selected {
        filter: brightness(0.75);
    }
</style>

<div class="mx-auto bg-white p-6 rounded-lg shadow-lg mt-6 min-h-[90vh] flex flex-col">
    <h1 class="text-3xl text-center font-bold mb-4">Pending Applications & Log Requests</h1>
    <div class="w-3/4 h-[1px] bg-gray-300 mx-auto mb-6"></div>

    <!-- Tabs for Filtering -->
    <div class="flex space-x-4 mt-4">
        <button class="filter-btn bg-blue-500 text-white px-4 py-2 rounded-md"
            onclick="filterApplicationsLogRequests('pending-applications', this)" data-default>
            <span class="font-bold">Pending Applications</span>
        </button>
        <button class="filter-btn bg-green-500 text-white px-4 py-2 rounded-md"
            onclick="filterApplicationsLogRequests('pending-log-requests', this)">
            <span class="font-bold">Pending Log Requests</span>
        </button>
    </div>

    <!-- Applications Section -->
    <div id="pending-applications" class="mt-6">
        <h2 class="text-xl font-semibold">Volunteer Applications</h2>

        <div class="grid grid-cols-2 gap-6 mt-4">
            {% for application in applications %}
                <div class="bg-gray-100 p-4 rounded-lg shadow-md flex justify-between items-center space-x-4">
                    <!-- Left: Profile + Info -->
                    <div class="flex items-center space-x-4">
                        <!-- Clickable Profile Picture -->
                        <a href="{% url 'volunteers_organizations:profile' application.volunteer.account_uuid %}">
                            <img src="{{ application.volunteer.volunteer.profile_img }}" alt="Profile Picture"
                                class="w-16 h-16 rounded-full object-cover border border-gray-300 shadow-sm hover:ring hover:ring-blue-500 transition">
                        </a>
                
                        <!-- Info -->
                        <div>
                            <!-- Clickable Name -->
                            <a href="{% url 'volunteers_organizations:profile' application.volunteer.account_uuid %}" 
                            class="font-bold text-gray-900 hover:text-blue-600 transition">
                                {{ application.volunteer.volunteer.first_name }} {{ application.volunteer.volunteer.last_name }}
                            </a>
                            <p><strong>Opportunity:</strong> {{ application.volunteer_opportunity.title }}</p>
                            <p><strong>Applied as Group:</strong> 
                                {% if application.as_group %} Yes ({{ application.no_of_additional_volunteers }}) 
                                {% else %} No {% endif %}
                            </p>
                            <p class="text-sm text-gray-500"><strong>Submitted on:</strong> {{ application.created_at|date:"M d, Y H:i" }}</p>
                        </div>
                    </div>
                
                    <!-- Right: Buttons -->
                    <div class="flex space-x-2">
                        <button onclick="acceptApplication('{{ application.volunteer_opportunity_application_id }}', '{{ application.volunteer.account_uuid }}', '{{ application.volunteer_opportunity.volunteer_opportunity_id }}', '{{ application.volunteer_opportunity.ongoing|lower }}')"
                                class="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                </svg>
                                <span class="font-bold">Accept</span>
                        </button>
                        <button class="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg"
                                hx-patch="{% url 'opportunities_engagements:reject_application' application.volunteer_opportunity_application_id %}"
                                hx-trigger="click"
                                hx-target="#loading-modal-content">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                </svg>
                                <span class="font-bold">Reject</span>
                        </button>
                    </div>
                </div>
            {% empty %}
                <p class="text-gray-500">No pending applications.</p>
            {% endfor %}
        </div>
    </div>

    <!-- Log Requests Section -->
    <div id="pending-log-requests" class="mt-6 hidden">
        <h2 class="text-xl font-semibold">Engagement Log Requests</h2>

        <div class="grid grid-cols-2 gap-6 mt-4">
            {% for log in log_requests %}
                <div class="bg-gray-100 p-4 rounded-lg shadow-md">
                    <h3 class="font-bold">{{ log.volunteer_engagement.volunteer_opportunity_application.volunteer.volunteer.first_name }} {{ log.volunteer_engagement.volunteer_opportunity_application.volunteer.volunteer.last_name }}</h3>
                    <p><strong>Opportunity:</strong> {{ log.volunteer_engagement.volunteer_opportunity_application.volunteer_opportunity.title }}</p>
                    <p><strong>Logged Hours:</strong> {{ log.no_of_hours }} hrs</p>
                    <p class="text-sm text-gray-500"><strong>Submitted:</strong> {{ log.created_at|date:"M d, Y" }}</p>

                    <div class="flex space-x-2 mt-3">
                        <button class="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg"
                            hx-patch="{% url 'opportunities_engagements:approve_engagement_log' log.volunteer_engagement_log_id %}"
                            hx-trigger="click"
                            hx-target="#loading-modal-content">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                            </svg>
                            <span class="font-bold">Approve</span>
                        </button>
                        <button class="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg"
                            hx-patch="{% url 'opportunities_engagements:reject_engagement_log' log.volunteer_engagement_log_id %}"
                            hx-trigger="click"
                            hx-target="#loading-modal-content">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                            </svg>
                            <span class="font-bold">Reject</span>
                        </button>
                    </div>
                </div>
            {% empty %}
                <p class="text-gray-500">No pending log requests.</p>
            {% endfor %}
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const defaultBtn = document.querySelector('.filter-btn[data-default]');
            if (defaultBtn) {
                defaultBtn.click();
            }
        });
    </script>
</div>
{% endblock %}

cm3070final/opportunities_engagements/templates/opportunities_engagements/opportunities_organization.html
{% extends 'base/base_authenticated.html' %}
{% load static %}
{% block title %}Opportunities{% endblock %}
{% block auth_content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css">
<script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_PLACES_API_KEY }}&libraries=places&callback=initAutocomplete" async defer></script>
<script src="{% static 'js_frontend-scripts/profile-processes.js' %}"></script>
<script src="{% static 'js_frontend-scripts/preferences-processes.js' %}"></script>
<script src="{% static 'js_frontend-scripts/opportunities-engagements-processes.js' %}"></script>

<div class="mx-auto justify-start bg-gray-100 px-4 min-h-[90vh] flex flex-col items-center">
    <div class="w-full bg-white p-6 rounded-lg shadow-lg flex-grow">
        <!-- Page Header -->
        <div class="flex justify-between items-center mt-6 mb-4 border-b pb-4">
            <h1 class="text-3xl font-bold text-gray-800">My Opportunities</h1>
            <button onclick="document.getElementById('create-opportunity-modal').classList.remove('hidden'); document.getElementById('create-opportunity-modal').classList.add('flex')" 
                    class="bg-blue-600 font-bold text-white px-4 py-2 rounded-md shadow-md hover:bg-blue-700 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg">
                + Create Opportunity
            </button>
        </div>

        <!-- Filter Tabs -->
        <div class="flex space-x-4 border-b">
            <button class="tab-btn py-2 px-4 text-gray-800 border-b-2 border-transparent hover:border-blue-600 focus:border-blue-600" 
                    onclick="filterOpportunities('upcoming')">
                    <span class="font-bold">Upcoming</span>
            </button>
            <button class="tab-btn py-2 px-4 text-gray-800 border-b-2 border-transparent hover:border-blue-600 focus:border-blue-600"
                    onclick="filterOpportunities('completed')">
                <span class="font-bold">Completed</span>
            </button>
            <button class="tab-btn py-2 px-4 text-gray-800 border-b-2 border-transparent hover:border-blue-600 focus:border-blue-600"
                    onclick="filterOpportunities('cancelled')">
                <span class="font-bold">Cancelled</span>
            </button>
        </div>

        <!-- Opportunity Cards -->
        <div id="opportunities-container" class="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4 flex-grow">
            {% for opportunity in all_opportunities %}
                <div class="opportunity-card bg-white p-6 rounded-lg shadow-md border border-gray-200 cursor-pointer transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-gray-50"
                    data-status="{{ opportunity.status }}"
                    data-url="{% url 'opportunities_engagements:opportunity' opportunity_id=opportunity.volunteer_opportunity_id %}"
                    onclick="window.location.href=this.getAttribute('data-url')">
                    <h2 class="text-xl font-semibold text-gray-900">{{ opportunity.title }}</h2>
                    <p class="text-gray-700 mt-1">{{ opportunity.description }}</p>

                    <!-- Details -->
                    <div class="mt-2 text-gray-600 text-sm">
                        <p><strong>Opportunity Type:</strong>{% if opportunity.ongoing %} Ongoing{% else %} One-Time{% endif%}</p>
                        <p><strong>Work Type:</strong> {{ opportunity.work_basis|title }}</p>
                        <p><strong>Duration:</strong> {{ opportunity.duration|title }}</p>
                        {% if opportunity.ongoing %}
                            <p><strong>Days Available:</strong> {{ opportunity.days_of_week|join:", "|title }}</p>
                        {% else %}
                            <p><strong>Opportunity Date:</strong> {{ opportunity.opportunity_date }}</p>
                            <p><strong>From:</strong> {{ opportunity.opportunity_time_from }}</p>
                            <p><strong>To:</strong> {{ opportunity.opportunity_time_to }}</p>
                            {% endif %}
                        <p><strong>Location:</strong> {{ opportunity.required_location.formatted_address }}</p>
                        <p><strong>Area of Work:</strong> {{ opportunity.area_of_work|title }}</p>
                        <p><strong>Skills Required:</strong> {{ opportunity.requirements|join:", "|title }}</p>
                        <p><strong>Languages:</strong> {{ opportunity.languages|join:", " }}</p>
                        {% if opportunity.application_deadline %}
                            <p><strong>Application Deadline:</strong> {{ opportunity.application_deadline }}</p>
                        {% endif %}
                        {% if opportunity.slots %}
                            <p><strong>Slots Available:</strong> {{ opportunity.slots }}</p>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <p class="text-center text-gray-500 mt-4">No opportunities available.</p>
            {% endfor %}
        </div>
    </div>
</div>

<!--Include this modal so that the organization can create a new opportunity-->
{% include 'opportunities_engagements/partials/create_opportunity_modal.html' %}
{% endblock %}