cm3070final/base/urls.py
from django.urls import path
from .views import home_view

urlpatterns = [
    path('', home_view, name='home'),
]

cm3070final/volontera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpRequest
from base import views as base_views

# Custom error handlers
handler404 = base_views.custom_404
handler403 = base_views.custom_403
handler500 = base_views.custom_500
handler400 = base_views.custom_400

def root_redirect_view(request: HttpRequest):
    if request.user.is_authenticated:
        return redirect(f'/volunteers-organizations/profile/{request.user.account_uuid}')
    return redirect('/accounts/auth/?type=login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root_redirect_view),
    path('home/', lambda request: redirect('/')), # Redirect to home
    path('accounts/', include('accounts_notifs.urls')),
    path('volunteers-organizations/', include('volunteers_organizations.urls')),
    path('oauth/', include('allauth.urls')),
    path('opportunities-engagements/', include('opportunities_engagements.urls')),
    path('chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cm3070final/volunteers_organizations/urls.py
from django.urls import path
from .views import signup_final, profile_view, search_profiles_view, update_profile_view, preferences_view
from .api import get_user_profile, get_all_followers, get_following, create_following, delete_following, get_endorsements, create_endorsement, delete_endorsement, get_status_posts, create_status_post, delete_status_post, get_search_profiles, create_volunteer_preferences, create_organization_preferences, get_organization_preferences, get_volunteer_preferences, update_volunteer_preferences, update_organization_preferences, donate_volontera_points

app_name = 'volunteers_organizations'

urlpatterns = [
    # View endpoints
    path('signup_final/', signup_final, name='signup_final'),
    path('profile/<uuid:account_uuid>', profile_view, name='profile'),
    path('search_profiles/', search_profiles_view, name='search_profiles'),
    path('update_profile/', update_profile_view, name='update_profile'),
    path('preferences/', preferences_view, name='preferences'),

    ### REST API Endpoints ###
    # Account profile endpoints
    path('api/profile/<uuid:account_uuid>', get_user_profile, name='get_user_profile'),
    
    # Following endpoints
    path('api/following/get_all_followers/<uuid:account_uuid>', get_all_followers, name='get_all_followers'),
    path('api/following/get_following/<uuid:account_uuid>', get_following, name='get_following'),
    path('api/following/create_following/<uuid:account_uuid>', create_following, name='create_following'),
    path('api/following/delete_following/<uuid:account_uuid>', delete_following, name='delete_following'),
    
    # Endorsement endpoints
    path('api/endorsements/get_endorsements/<uuid:account_uuid>', get_endorsements, name='get_endorsements'),
    path("api/endorsements/create_endorsement/<uuid:account_uuid>/", create_endorsement, name="create_endorsement"),
    path("api/endorsements/delete_endorsement/<uuid:id>/", delete_endorsement, name="delete_endorsement"),
    
    # Status post endpoints
    path("api/status_posts/get_status_posts/<uuid:account_uuid>/", get_status_posts, name="get_status_posts"),
    path("api/status/create_status_post/", create_status_post, name="create_status_post"),
    path("api/status/delete_status_post/<uuid:id>/", delete_status_post, name="delete_status_post"),
    
    # Search profiles endpoints
    path("api/search/get_search_profiles/", get_search_profiles, name="get_search_profiles"),
    
    #Volunteer Matching/Organization Preferences
    path('api/volunteer_matching_preferences/create_volunteer_preferences/', create_volunteer_preferences, name='create_volunteer_preferences'),
    path('api/volunteer_matching_preferences/get_volunteer_preferences/', get_volunteer_preferences, name='get_volunteer_preferences'),
    path('api/volunteer_matching_preferences/update_volunteer_preferences/', update_volunteer_preferences, name='update_volunteer_preferences'),
    path('api/organization_preferences/create_organization_preferences/', create_organization_preferences, name='create_organization_preferences'),
    path('api/organization_preferences/get_organization_preferences/', get_organization_preferences, name='get_organization_preferences'),
    path('api/organization_preferences/update_organization_preferences/', update_organization_preferences, name='update_organization_preferences'),

    # Donate endpoints
    path('api/donate/donate_volontera_points/<uuid:organization_id>', donate_volontera_points, name='donate_volontera_points'),
]

cm3070final/volunteers_organizations/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Account
from .api import get_user_profile, get_following, get_all_followers, get_status_posts, get_endorsements, get_search_profiles, get_volunteer_preferences, get_organization_preferences
from opportunities_engagements.api import get_engagement_logs, get_upcoming_opportunities
from .forms import VolunteerForm, OrganizationForm
from .models import Volunteer, Organization, VolunteerMatchingPreferences, OrganizationPreferences
import json
import pycountry
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from accounts_notifs.helpers import has_unread_notifications
from chats.helpers import has_unread_messages
from django.utils.dateparse import parse_datetime, parse_date

    
def signup_final(request):
    account_data=request.session.get('account_data')

    if not account_data:
        return redirect('accounts_notifs:authentication', type='signup')
    
    user_type=account_data.get('user_type')
    form=None

    if user_type=='volunteer':
        form=VolunteerForm(request.POST, request.FILES)
    elif user_type=='organization':
        form=OrganizationForm(request.POST, request.FILES)

    if request.method=='POST' and form.is_valid():
        account = Account(**account_data)
        print(account)
        account.set_password(account_data.get('password'))
        account.save()

        user=form.save(commit=False)
        user.account=account
        user.save()
        request.session.pop('account_data', None)

        return render(request, 'volunteers_organizations/partials/signup_success_modal.html', status=200)
    
    return render(request, 'volunteers_organizations/signup_final.html', {
        'form': form,
        'user_type': user_type
    })

@login_required
def profile_view(request, account_uuid):
    is_own_profile = request.user.account_uuid == account_uuid
    context ={'is_own_profile': is_own_profile}
    has_unread = has_unread_notifications(request.user)
    has_unread_msg = has_unread_messages(request.user)
    context["has_unread_notifications"] = has_unread
    context["has_unread_messages"] = has_unread_msg

    if not is_own_profile:
        # Get user profile data
        user_profile = get_user_profile(request, account_uuid)
        if user_profile.status_code==404:
            context['message'] = 'Profile not found'
        else:
            user_profile = json.loads(user_profile.content)
            context['user_profile'] = user_profile

        # Get whether logged-in user is following the profile user
        is_following = get_following(request, account_uuid)
        if is_following.status_code==404:
            context['message'] = 'Following not found'
        else:
            context['is_following'] = is_following.data

        # Get follower count of profile user
        followers = get_all_followers(request, account_uuid)
        if followers.status_code==404:
            context['message'] = 'Followers not found'
        else:
            context['followers_count'] = followers.data

        if user_profile["account"]["user_type"] == "volunteer":
            engagement_logs = get_engagement_logs(request, account_uuid)
            if engagement_logs.status_code==404:
                context['message'] = 'Engagement logs not found'
            else:
                logs_data = engagement_logs.data
                for log in logs_data:
                    if isinstance(log.get("created_at"), str):
                        log["created_at"] = parse_datetime(log["created_at"])
                context['engagement_logs'] = logs_data
                context['total_hours'] = sum(log.get("no_of_hours", 0) for log in logs_data)
                context["unique_organizations"] = len(set(
                        log["volunteer_engagement"]
                        .get("volunteer_opportunity_application", {})
                        .get("volunteer_opportunity", {})
                        .get("organization", {})
                        .get("organization", {})
                        .get("organization_name", "Unknown")
                        for log in logs_data
                    ))
        elif user_profile["account"]["user_type"] == "organization":
            upcoming_opportunities = get_upcoming_opportunities(request, account_uuid)
            if upcoming_opportunities.status_code==404:
                context['message'] = 'Upcoming opportunities not found'
            else:
                upcoming_opportunities = upcoming_opportunities.data
                for opportunity in upcoming_opportunities:
                    if isinstance(opportunity["opportunity_date"], str):
                        opportunity["opportunity_date"] = parse_date(opportunity["opportunity_date"])
                context['upcoming_opportunities'] = upcoming_opportunities

    else:
        followers = get_all_followers(request, account_uuid)
        if followers.status_code==404:
            context['message'] = 'Followers not found'
        else:
            context['followers_count'] = followers.data
        
        if request.user.is_volunteer():
            engagement_logs = get_engagement_logs(request, account_uuid)
            if engagement_logs.status_code==404:
                context['message'] = 'Engagement logs not found'
            else:
                logs_data = engagement_logs.data
                for log in logs_data:
                    if isinstance(log.get("created_at"), str):
                        log["created_at"] = parse_datetime(log["created_at"])
                context['engagement_logs'] = logs_data
                context['total_hours'] = sum(log.get("no_of_hours", 0) for log in logs_data)
                context["unique_organizations"] = len(set(
                        log["volunteer_engagement"]
                        .get("volunteer_opportunity_application", {})
                        .get("volunteer_opportunity", {})
                        .get("organization", {})
                        .get("organization", {})
                        .get("organization_name", "Unknown")
                        for log in logs_data
                    ))
        elif request.user.is_organization():
            upcoming_opportunities = get_upcoming_opportunities(request, account_uuid)
            if upcoming_opportunities.status_code==404:
                context['message'] = 'Upcoming opportunities not found'
            else:
                upcoming_opportunities = upcoming_opportunities.data
                for opportunity in upcoming_opportunities:
                    if isinstance(opportunity["opportunity_date"], str):
                        opportunity["opportunity_date"] = parse_date(opportunity["opportunity_date"])
                context['upcoming_opportunities'] = upcoming_opportunities
        
        # If the user is viewing their own profile, check if they are a volunteer and have not set their matching preferences, or if they are an organization and have not set their preferences
        show_preferences_modal = False
        if request.user.is_volunteer() and not VolunteerMatchingPreferences.objects.filter(volunteer=request.user.volunteer).exists():
            show_preferences_modal = True
            context['show_preferences_modal'] = show_preferences_modal

            # Dynamically pass the choices to the modal preferences template
            context["days_of_week"] = [choice[0] for choice in VolunteerMatchingPreferences.DAYS_OF_WEEK_CHOICES]
            context["work_types"] = [choice[0] for choice in VolunteerMatchingPreferences.WORK_TYPE_CHOICES]
            context["durations"] = [choice[0] for choice in VolunteerMatchingPreferences.DURATION_CHOICES]
            context["fields_of_interest"] = [choice[0] for choice in VolunteerMatchingPreferences.FIELDS_OF_INTEREST_CHOICES]
            context["skills"] = [choice[0] for choice in VolunteerMatchingPreferences.SKILLS_CHOICES]

            languages = [(lang.alpha_2, lang.name) for lang in pycountry.languages if hasattr(lang, 'alpha_2')]
            context["languages"] = languages

        elif request.user.is_organization() and not OrganizationPreferences.objects.filter(organization=request.user.organization).exists():
            show_preferences_modal = True
            context['show_preferences_modal'] = show_preferences_modal

    status_posts = get_status_posts(request, account_uuid)
    if status_posts.status_code==404:
        context['message'] = 'Status posts not found'
    else:
        context['status_posts'] = status_posts.data

    endorsements = get_endorsements(request, account_uuid)
    if endorsements.status_code==404:
        context['message'] = 'Endorsements not found'
    else:
        context['endorsements'] = endorsements.data

    return render(request, 'volunteers_organizations/profile.html', context)

@login_required
def search_profiles_view(request):
    account = request.user
    has_unread = has_unread_notifications(account)
    has_unread_msg = has_unread_messages(account)
    search_response = get_search_profiles(request)

    if search_response.status_code != 200:
        return render(request, 'volunteers_organizations/search_profiles.html', {'message': 'Profiles not found'})

    search_results = search_response.data.get("results", [])

    paginator = Paginator(search_results, 10)
    page_number = request.GET.get('page')
    paginated_results = paginator.get_page(page_number)

    return render(request, 'volunteers_organizations/search_profiles.html', {
        'results': paginated_results,
        'query': request.GET.get('q'),
        'has_unread_notifications': has_unread,
        'has_unread_messages': has_unread_msg
    })

@login_required
def update_profile_view(request):
    account = request.user
    has_unread = has_unread_notifications(account)

cm3070final/volunteers_organizations/templates/volunteers_organizations/preferences.html
{% extends 'base/base_authenticated.html' %}
{% load static %}
{% block title %}Preferences{% endblock %}
{% block auth_content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css">
<script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>

<!-- Event listener included here and not in event-listeners.js because event-listeners is loaded on every page, whislt this evetn listener is exclusively for profile.html page-->
<script src="{% static 'js_frontend-scripts/preferences-processes.js' %}"></script>
<script src="{% static 'js_frontend-scripts/profile-processes.js' %}"></script> <!--Importing to use updateContent()-->
<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_PLACES_API_KEY }}&libraries=places&callback=initAutocomplete" async defer></script>

<div class="mx-auto bg-white p-6 rounded-lg shadow-md relative mt-4">
    <!-- Title & Back Button -->
    <div class="flex items-center justify-between mb-4">
        <a href="{{ request.META.HTTP_REFERER|default:'#' }}" class="absolute left-5 top-5 px-2 py-2 bg-gray-700 text-white rounded-md shadow-sm transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-gray-600 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9.75 14.25 12m0 0 2.25 2.25M14.25 12l2.25-2.25M14.25 12 12 14.25m-2.58 4.92-6.374-6.375a1.125 1.125 0 0 1 0-1.59L9.42 4.83c.21-.211.497-.33.795-.33H19.5a2.25 2.25 0 0 1 2.25 2.25v10.5a2.25 2.25 0 0 1-2.25 2.25h-9.284c-.298 0-.585-.119-.795-.33Z" />
            </svg>
        </a>
        <h2 class="text-2xl font-bold text-center flex-1">Update Preferences</h2>
    </div>

    {% if user.volunteer %}
        <form id="preferences-form" 
            method="patch"
            hx-patch="{% url 'volunteers_organizations:update_volunteer_preferences' %}"
            hx-trigger="submit"
            hx-target="#loading-modal-content"
            hx-swap="innerHTML"
            data-redirect-url="{% url 'volunteers_organizations:profile' account_uuid=user.account_uuid %}"
            class="space-y-6">

            <!-- Location -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label for="location-input" class="block text-gray-700 font-semibold mb-2">Preferred Location</label>
                <input id="location-input" required="true" name="location_input" type="text" 
                    placeholder="Enter your preferred location"
                    value="{{ preferences.location.formatted_address|default:'' }}"
                    class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">
                
                <!-- Hidden input to store full JSON -->
                <input type="hidden" id="location-hidden" name="location" 
                    value="{{ preferences.location }}">
            </div>

            <!-- Languages -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label for="language-select" class="block text-gray-700 font-semibold mb-2">Languages</label>
                <select id="language-select" name="languages" multiple
                        class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 rounded-md outline-blue-600">
                    {% for code, lang in languages %}
                        <option value="{{ lang }}" {% if lang in preferences.languages %}selected{% endif %}>{{ lang }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- Availability -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-4">Availability (Days of the Week)</label>
                <div class="grid grid-cols-4 gap-4">
                    {% for day in days_of_week %}
                        <label class="flex items-center space-x-2">
                            <input type="checkbox" name="availability" value="{{ day }}"
                                {% if day in preferences.availability %}checked{% endif %}
                                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500">
                            <span class="text-gray-800">{{ day|title }}</span>
                        </label>
                    {% endfor %}
                </div>
            </div>

            <!-- Preferred Work Type -->
            <div class="bg-gray-100 p-4 rounded-lg">                       
                <label class="block text-gray-700 font-semibold mb-2">Preferred Work Type</label>
                <select name="preferred_work_types"
                        class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md focus:ring-2 focus:ring-blue-600 focus:border-blue-600">
                    {% for type in work_types %}
                        <option value="{{ type }}" {% if type == preferences.preferred_work_types %}selected{% endif %}>
                            {{ type|title }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <!-- Preferred Duration -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-4">Preferred Duration</label>
                <div class="grid grid-cols-3 gap-4 mt-2">
                    {% for duration in durations %}
                        <label class="flex items-center space-x-2">
                            <input type="checkbox" name="preferred_duration" value="{{ duration }}"
                                {% if duration in preferences.preferred_duration %}checked{% endif %}
                                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500">
                            <span class="text-gray-800">{{ duration|title }}</span>
                        </label>
                    {% endfor %}
                </div>
            </div>

            <!-- Fields of Interest -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-4">Fields of Interest (Max 5)</label>
                <div class="grid grid-cols-3 gap-4">
                    {% for field in fields_of_interest %}
                        <label class="flex items-center space-x-2">
                            <input type="checkbox" name="fields_of_interest" value="{{ field }}"
                                {% if field in preferences.fields_of_interest %}checked{% endif %}
                                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500">
                            <span class="text-gray-800">{{ field|title }}</span>
                        </label>
                    {% endfor %}
                </div>
            </div>

            <!-- Skills -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label class="block text-gray-700 font-semibold mb-4">Skills (Max 10)</label>
                <div class="grid grid-cols-4 gap-4">
                    {% for skill in skills %}
                        <label class="flex items-center space-x-2">
                            <input type="checkbox" name="skills" value="{{ skill }}"
                                {% if skill in preferences.skills %}checked{% endif %}
                                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500">
                            <span class="text-gray-800">{{ skill|title }}</span>
                        </label>
                    {% endfor %}
                </div>
            </div>

            <!-- Buttons -->
            <div class="flex justify-center mt-10">
                <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-blue-700">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" />
                    </svg>
                    <span class="font-bold">Update Preferences</span>
                </button>
            </div>
        </form>
    {% elif user.organization %}
        <form id="preferences-form"
            method="patch"
            hx-patch="{% url 'volunteers_organizations:update_organization_preferences' %}"
            hx-trigger="submit"
            hx-target="#loading-modal-content"
            hx-swap="innerHTML"
            data-redirect-url="{% url 'volunteers_organizations:profile' account_uuid=user.account_uuid %}"
            class="space-y-6">

            <!-- Location -->
            <div class="bg-gray-100 p-4 rounded-lg">
                <label for="location-input" class="block text-gray-700 font-semibold mb-2">Main Location</label>
                <input id="location-input" required="true" name="location_input" type="text" 
                    placeholder="Enter your preferred location"
                    value="{{ preferences.location.formatted_address|default:'' }}"
                    class="w-full text-sm text-gray-800 bg-gray-100 focus:bg-transparent pl-4 pr-10 py-3.5 rounded-md outline-blue-600">

                <!-- Hidden input to store full JSON -->
                <input type="hidden" id="location-hidden" name="location" 
                    value='{{ preferences.location|default:"{}" }}'>
            </div>

            <!-- Buttons -->
            <div class="flex justify-center mt-10">
                <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-md flex items-center justify-center space-x-2 transition-transform duration-200 hover:scale-[1.02] hover:shadow-lg hover:bg-blue-700">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" />
                    </svg>
                    <span class="font-bold">Update Preferences</span>
                </button>
            </div>
        </form>
    {% endif %}
</div>
{% endblock %}

cm3070final/volunteers_organizations/templates/volunteers_organizations/search_profiles.html
{% extends 'base/base_authenticated.html' %}
{% load static %}
{% block title %}Search Results{% endblock %}
{% block auth_content %}
<div class="mx-auto p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-2xl font-bold text-center mb-6">Search Results for "{{ query }}"</h2>

    {% if results %}
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            {% for profile in results %}
                <a href="{{ profile.profile_url }}" class="block p-4 bg-gray-100 hover:bg-gray-200 transition duration-300 rounded-lg shadow-md ease-in-out hover:scale-[1.02] hover:shadow-lg">
                    <div class="flex items-center space-x-4">
                        <!-- Profile Image -->
                        <img src="{% if profile.profile_img %}{{ profile.profile_img }}
                            {% elif profile.first_name %}/static/images/default_volunteer.svg
                            {% else %}/static/images/default_organization.svg
                            {% endif %}"
                        class="w-16 h-16 rounded-full object-cover"
                        alt="Profile Image">
                        
                        <!-- Profile Info -->
                        <div>
                            <p class="text-lg font-semibold text-gray-800">
                                {% if profile.first_name %}
                                    {{ profile.first_name }} {{ profile.last_name }}
                                {% else %}
                                    {{ profile.organization_name }}
                                {% endif %}
                            </p>
                            <p class="text-sm text-gray-600">
                                {% if profile.first_name %} Volunteer {% else %} Organization {% endif %}
                            </p>
                            <p class="text-xs text-gray-500">{{ profile.followers }} Followers</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

        <!-- Pagination Controls -->
        <div class="flex justify-center mt-6 space-x-2">
            {% if results.has_previous %}
                <a href="?q={{ query }}&page=1" class="px-3 py-1 border rounded-md">First</a>
                <a href="?q={{ query }}&page={{ results.previous_page_number }}" class="px-3 py-1 border rounded-md">Previous</a>
            {% endif %}
            
            <span class="px-3 py-1 bg-gray-200 rounded-md">Page {{ results.number }} of {{ results.paginator.num_pages }}</span>
            
            {% if results.has_next %}
                <a href="?q={{ query }}&page={{ results.next_page_number }}" class="px-3 py-1 border rounded-md">Next</a>
                <a href="?q={{ query }}&page={{ results.paginator.num_pages }}" class="px-3 py-1 border rounded-md">Last</a>
            {% endif %}
        </div>
    {% else %}
        <p class="text-center text-gray-500">No results found.</p>
    {% endif %}
</div>
{% endblock %}